### ISSUE TITLE
Question on durable sink

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [mishamyte/serilog-sinks-grafana-loki#12]
I have a potentially stupid question:

Using a [Durable sink](https://github.com/mishamyte/serilog-sinks-grafana-loki/wiki/Durable-file-size-rolled-Grafana-Loki-sink):
"_A durable sink will persist log events on disk before sending them, thus protecting against data loss after a system or process restart._"

Will this protect agains a restart / unavailability of loki ?
Or / and a restart of the client application that is logging?

e.g. loki is unavailable, the client app is buffering in files, the client is restarted.
Loki becomes available again, will old bufferfiles be read and sent to loki in chronological order to prevent logstream out of order errors, or will these buffer files only be an emergency offline backup?
I have not yet had time to experiment with it.

Thank you.

**Comment by mishamyte** [comment]
Hi, @Mario-Hofstaetter. I'm going to deprecate durable mode in 5.* release due to some issues. It is more limited in a core features that a normal mode
