### ISSUE TITLE
Dear author： I’d like to know that how to use serilog.loki to establish a customizing client to make an index for writing logs as Elasticsearch.

### ISSUE THREAD

**Issue by huzitao** [mishamyte/serilog-sinks-grafana-loki#15]
Dear author： I’d like to know that how to use serilog.loki to establish a customizing client to make an index for writing logs as Elasticsearch.

**Comment by mishamyte** [comment]
Hello, @huzitao!

Sorry, can't get about what index do u talk? Do u mean a search index, used for indexation of log entries?

**Comment by huzitao** [comment]
yes

**Comment by mishamyte** [comment]
Main principles of Loki differs from a principles of Elastic Search.

Traditional systems like ELK parse log strings entirely, including fields with a lot of unique values (for example, UserId from log entry) and save parsed data into big indexes. It has advantage that queries could be done fast, cause all required data is in the index. But the disadvantage is an index grows and become very large (in most cases size of the index could be almost equal to a logs size). 

Loki works in another way. It's approach requires only most critical data must be extracted into index (called **labels**). So u have a possibility to find data, using filtration by datetime & labels. And the u could do an additional filtering with **LogQL** (it's kinda a regex & substring-based language).

U could find more details in [Loki documentation](https://grafana.com/docs/loki/latest/best-practices/current-best-practices/).


So, for that approach you should determine most important fields for indexing and setup the sync with _filtrationMode_ `Include` and _filtrationLabels_ list.

For example:
```csharp
ILogger logger = new LoggerConfiguration()
    .WriteTo.GrafanaLoki(
          "http://localhost:3100",
           filtrationMode: LokiLabelFiltrationMode.Include,
           filtrationLabels: new [] {"RequestId", "ClientIp", "SomeImportantLogValue"})
    .CreateLogger();
```

More examples of filtering are here in [tests](https://github.com/mishamyte/serilog-sinks-grafana-loki/blob/master/test/Serilog.Sinks.Grafana.Loki.Tests/HttpClientTests/RequestPayloadTests.cs)

**Comment by huzitao** [comment]
thank you very much

**Comment by huzitao** [comment]
Thank you for your help.  Meanwhile， i have another question. Does the loki client support custom labels to write logs？I need to write logs by costom labels at present.

**Comment by huzitao** [comment]
谢谢你的帮助我还有一个问题。洛基客户端支持自定义标签写日志吗？我目前需要使用自定义标签编写日志。

**Comment by huzitao** [comment]
Thank you for your help.  Meanwhile， i have another question. Does the loki client support custom labels to write logs？I need to write logs by custom labels at present.

**Comment by huzitao** [comment]
Thank you for your help.  Meanwhile， i have another question. Does the Loki client support custom labels to write logs？I need to write logs by custom labels at present.

**Comment by mishamyte** [comment]
@huzitao yes, you could use a global labels. They would append to every log entries from configured service.

```csharp
ILogger logger = new LoggerConfiguration()
    .WriteTo.GrafanaLoki(
          "http://localhost:3100",
            labels: new [] { new LokiLabel { Key = "app", Value = "payment"}})
    .CreateLogger();
```

You could find all options in project [wiki](https://github.com/mishamyte/serilog-sinks-grafana-loki/wiki/Grafana-Loki-sink)
