### ISSUE TITLE
Exception in sink when serializing exception with JSON formatting enabled

### ISSUE THREAD

**Issue by foresterLV** [mishamyte/serilog-sinks-grafana-loki#20]
Found issue when Redis exception (stackexchange redis library) is logged via Logger.LogError(x, "message"):

``testapp_1        | 2021-02-08T10:24:19.0994530Z Exception while emitting periodic batch from Serilog.Sinks.Http.Private.Sinks.HttpSink: System.NullReferenceException: Object reference not set to an instance of an object.
testapp_1        |    at Serilog.Formatting.Json.JsonValueFormatter.WriteQuotedJsonString(String str, TextWriter output)
testapp_1        |    at Serilog.Sinks.Grafana.Loki.LokiJsonTextFormatter.SerializeException(TextWriter output, Exception exception, Int32 level)
testapp_1        |    at Serilog.Sinks.Grafana.Loki.LokiJsonTextFormatter.SerializeException(TextWriter output, Exception exception, Int32 level)
testapp_1        |    at Serilog.Sinks.Grafana.Loki.LokiJsonTextFormatter.Format(LogEvent logEvent, TextWriter output, IEnumerable`1 labels)
testapp_1        |    at Serilog.Sinks.Grafana.Loki.LokiBatchFormatter.GenerateEntry(LogEvent logEvent, ITextFormatter formatter, LokiStream stream, IEnumerable`1 labels)
testapp_1        |    at Serilog.Sinks.Grafana.Loki.LokiBatchFormatter.Format(IEnumerable`1 logEvents, ITextFormatter formatter, TextWriter output)
testapp_1        |    at Serilog.Sinks.Http.Private.Sinks.HttpSink.FormatPayload(IEnumerable`1 logEvents)
testapp_1        |    at Serilog.Sinks.Http.Private.Sinks.HttpSink.EmitBatchAsync(IEnumerable`1 logEvents)
testapp_1        |    at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()``

using 5.1.0-beta nuget package and enabling json formatting. It looks like after this happens sink stops sending anything to the Loki.

Either way when it works logs shows up nicely in the Grafana/Loki and can be parsed with "| json" stuff. :)
Thanks.

**Comment by mishamyte** [comment]
Hello, @foresterLV!

Thank you. We will look at this bug in advance.
Could you, please. share a test app, which could be used for reproducing this issue?
It could reduce the amount of time, needed for investigation

**Comment by foresterLV** [comment]
Hi @mishamyte,

I tried to reproduce it in a smaller app and it turns out it could be Redis-related - it happens randomly and is hard to reproduce (depends on timings I suppose). 
If you look into Redis library code here - https://github.com/StackExchange/StackExchange.Redis/blob/8612fb8a9278822c87d5476819325a7438e596ca/src/StackExchange.Redis/ConnectionMultiplexer.cs#L2757
- it is doing quite weird stuff on exception objects - calling GC.KeepAlive, throwing it and then attaching to a task. 

So its seems that either Exception object is modified while being serialized in sink library or something happens due to garbage collection. Either way I think what needs to be fixed is that exception in sink should not stop logging from working completely even if such event occurs during serialization - thats probably would be best fix in this situation (i.e. prevent sink from giving up on all messages after one serialization failed). In mean time Il try to understand what Redis library is doing there and how it can be avoided.

Thank you.

**Comment by mishamyte** [comment]
Thanks for information, @foresterLV!

This is kinda interesting case.
I'm not sure that behaviour with stopping could be fixed gracefully by sink.

But I will do an additional investigation and will publish a patch, if possible

**Comment by AnderssonPeter** [comment]
Just guessing here but is the exception.Message null?

**Comment by foresterLV** [comment]
It might be @AnderssonPeter, but it seems to be threading and timing related - its not easily to reproduce in simple app with few threads. 
I.e. in general Message is not null, but it looks like exception object is either modified while being serialized in sink due to strange bug in Redis, or its went through garbage collector just before serialization or something... 
My suggestion would be adding some try/catch block around serialization code so that if it crashes the sink will not cease working completely after that... Because what I see right now is that if such exception occurs in sink it will not send anything to the loki anymore (or maybe because it will try to serialize that "poisoned" exception again and again? havent investigated sink code yet).

Otherwise I think this bug can be closed as its true source seems to be not in sink but in library (Redis) which is doing weird stuff with exception objects in async methods.

**Comment by AnderssonPeter** [comment]
It seems [exception.message](https://docs.microsoft.com/en-us/dotnet/api/system.exception.message?view=net-5.0) allows null, we should add a null check before trying to serialize it.

It doesn't look like you can modify a exception as all its properties are readonly.

**Comment by mishamyte** [comment]
Hm, so I don't see how reproduce this behavior.
But, let this bug will be open a while.
I need a lil more time to prepare a release (finish implementing of tests & etc), so maybe we will have some additional details from somebody, who could face the same issue

**Comment by AnderssonPeter** [comment]
What happens when we get a exception while serializing, does it just throw away that `LogEntry` or does it explode and stop logging (or even worse does it just start consuming more and more memory)?

**Comment by foresterLV** [comment]
@AnderssonPeter in my experience after such exception happens all the log events stops from being delivered to Loki, so yeah its explode and stops logging anything.
So if you can simulate that exception and make sure that logging do not stop working after that - that will be fine fix for me.
