### ISSUE TITLE
Update dependency to Serilog.Sinks.Http v8

### ISSUE THREAD

**Issue by mishamyte** [mishamyte/serilog-sinks-grafana-loki#30]
Author prepares new major release, which deprecates some dep sinks (like PeriodicBatching & RollingFile)
Also, improves work with batches & another impovements.

For GrafanaLoki it could fix the issue, when the first message of log is missed (it is a floating bug, which can be observed on our CI).
+new configuration possibilities 

**Now Serilog.Sinks.Http in the beta, should wait for a stable build for release**

**Comment by mishamyte** [comment]
@AnderssonPeter  have u faced this issue with a lost of first log event on real environments recently?

**Comment by mishamyte** [comment]
Usage of `Serilog.Sinks.Http` could not be continued according to [this discussion](https://github.com/FantasticFiasco/serilog-sinks-http/issues/195)
So we can't update dep to v8, but need to remove this dep & implement a major changes to the codebase. This should be done in #31

**Comment by AnderssonPeter** [comment]
@mishamyte We still dont use this is production so i'm not 100% sure if we lost any packages, but it should be fairly easy to test with a unit test?

**Comment by mishamyte** [comment]
@AnderssonPeter yep, it's tested, so this is the source of my suggestions. But, anyway, all could change, due to new info, so I will look at this behavior in a new implementation
