### ISSUE TITLE
Configuration Option to not generate property labels

### ISSUE THREAD

**Issue by teian** [mishamyte/serilog-sinks-grafana-loki#4]
It would be awesome to not generate Labels for all properties. In our stack we're making heavy use of properties and this generates a gazillion different labels which is not ideal to have since it leads to a generation of unessessary extra log streams which slow down the logging alltogether. Therefore I propose a configuration switch to exclude generating Labels for every property since excluding them one by one is not really feasible if we're talking about hundreds of them.

**Comment by mishamyte** [comment]
Yes, this is a good concern. We faced this behavior too. 

Now I see the solution like mode (by including, by excluding) and list of labels, would be used by this mode. 

Would it be helpful for your problem?

**Comment by teian** [comment]
Sounds good to me. question is who wins if both are set. is the behaviour include > exclude or vise versa?

**Comment by mishamyte** [comment]
As for me this behaviors are opposite. Cause, something like IncludeOnly will define a list of labels, which will be in the output. Another ones would be kicked off.

Also, for now I think it would be just simple binary behavior, mb, in the future it will be extended.
Cause, there is a [Serilog Expressions](https://github.com/serilog/serilog-expressions), which could be used for global filtering of events.

And this feature will focus only on the labels.

**Comment by teian** [comment]
I see, this would work out for me.

**Comment by teian** [comment]
I implemented this change in PR #5

**Comment by mishamyte** [comment]
@teian thank you for your contribution, but I think it is correct partially.

1. We don't want to break backwards functionality
2. Also, we don't want to replace exclude with includes. We want to keep both with priority (include > exlude).
3. Also I see some logical misses (some inversions are missed)

I think, I will have a time for this changes tommorow

**Comment by mishamyte** [comment]
@teian sorry for delay, but this feature is implemented in [v4.0.0](https://github.com/mishamyte/serilog-sinks-grafana-loki/releases/tag/v4.0.0), Please, update the package

**Comment by teian** [comment]
No problem at all, thanks for the time and work!
